config/routes.rb
Rails.application.routes.draw do

  resources :payments
  devise_for :users

  get 'admins/show'

  get 'dashboard', to: "admins#show"

  #get 'admins/stats'

  get 'welcome/index'
  # get 'campaigns/:id/search' to: ''

  root to: "welcome#index"

  resources :campaigns do 
  	resources :subscribers, only: [:new, :create]
  	resources :prizes
  end 
 
  get 'campaigns/:id/stats', to: "campaigns#stats", as: "stats"
  get 'campaigns/:id/admin', to: "campaigns#admin", as: "admin"
  get 'campaigns/:id/activate', to: 'campaigns#activate', as: "activate"


end

app/models/payment.rb
class Payment < ApplicationRecord
	
	def do_deposit_transaction(type, stripe_token)
	  amount = Transaction.amount_for_type(type)
	  coupon = UserCoupon.coupon_for_amount(amount)

	  card = save_credit_card(stripe_token)
	  if deposited = deposit(amount, card)
	    subscribe if type == 'subscription'
	    create_coupon(coupon) if coupon

	    deposited
	  end
	end
	
	def deposit(amount, card)
	    customer = stripe_customer

	    Stripe::Charge.create(
	      amount: 500,
	      currency: 'usd',
	      customer: customer.id,
	      card: card.id,
	      description: "Charge for #{email}"
	    )

	    customer.account_balance += amount
	    customer.save
	rescue => e
	    false
	end

	def stripe_customer
    	Stripe::Customer.retrieve(stripe_customer_id)
	end

	# Set your secret key: remember to change this to your live secret key in production
	# See your keys here: https://dashboard.stripe.com/account/apikeys
	Stripe.api_key = "sk_test_npj2EvhDN6NsqKouOMHUTQ5i"

	# Token is created using Stripe.js or Checkout!
	# Get the payment token submitted by the form:
	token = params[:stripeToken]

	# Charge the user's card:
	charge = Stripe::Charge.create(
	  :amount => 1000,
	  :currency => "usd",
	  :description => "Example charge",
	  :source => token,
	)	
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  def new
  end

  def create
    if stripe_token = params[:stripe_token]
      if current_user.do_deposit_transaction(params[:payment_type], stripe_token)
        flash[:notice] = 'Card charged successfully'
      else
        flash[:alert] = 'Some error happened while charging you, please double check your card details'
      end
    else
      flash[:alert] = 'You did not submit the form correctly'
    end

    redirect_to new_payment_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.fetch(:payment, {})
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= stripe_javascript_tag %>
<%= form_tag payments_path, id: 'card-details' do %>
  <div class="payment-errors"></div>

  <div>
    <label for="card-number">Card Number:</label>
    <input id="card-number" type="text" data-stripe="number" />
  </div>

  <div>
    <label for="card-exp-month">Card Expiry Month:</label>
    <input id="card-exp-month" type="text" data-stripe="exp_month" />
  </div>

  <div>
    <label for="card-exp-year">Card Expiry Year:</label>
    <input id="card-exp-year" type="text" data-stripe="exp_year" />
  </div>

  <div>
    <label for="card-cvc">CVC:</label>
    <input id="card-cvc" type="text" data-stripe="cvc" />
  </div>

  <div>
    <label for="payment-type">Payment Type:</label>
    <select id="payment-type" name="payment_type">
      <option value="deposit">$20 Deposit</option>
      <option value="subscription">Monthly subscription, $9.97</option>
    </select>
  </div>

  <div>
    <input type="submit" value="Pay Now" />
  </div>
<% end %>

<%= link_to 'Back', payments_path %>


<script>
	$(function() {
  var stripeResponseHandler, $cardForm;

  $cardForm = $('#card-details');
  stripeResponseHandler = function(status, response) {
    if (response.error) {
      $cardForm.find('.payment-errors').text(response.error.message);
      $cardForm.find('input[type=submit]').prop('disabled', false);
    } else {
      var token = response.id;

      $cardForm.append($('<input type="hidden" name="stripe_token" />').val(token));
      $cardForm.get(0).submit();
    }
  };

  $cardForm.submit(function() {
    Stripe.card.createToken(this, stripeResponseHandler);

    return false;
  });
});
</script>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>