config/routes.rb
Rails.application.routes.draw do

  resources :payments
  devise_for :users

  get 'admins/show'

  get 'dashboard', to: "admins#show"

  #get 'admins/stats'

  get 'welcome/index'
  # get 'campaigns/:id/search' to: ''

  root to: "welcome#index"

  resources :campaigns do 
  	resources :subscribers, only: [:new, :create]
  	resources :prizes
  end 
 
  get 'campaigns/:id/stats', to: "campaigns#stats", as: "stats"
  get 'campaigns/:id/admin', to: "campaigns#admin", as: "admin"
  get 'campaigns/:id/activate', to: 'campaigns#activate', as: "activate"


end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :subscribers
	belongs_to :user, optional: true
	has_many :prizes
	validates :title, presence: true, length: { in: 6..72 }
	validates :duration, presence: true
	validate :activation

	# before_create :date_validation
	#validates_date :start_date, :after => lambda{ 0.days.ago }
	#validates_date :end_date, :after => :start_date, message: " Date is wrong"#

 	private
	#
	def activation
		if active && user_id.nil?
			errors.add(:active, " Must have a user account to activate")
		end
	end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

	before_action :set_campaign, only: [:edit, :show, :stats]

	def new
		@campaign = Campaign.new
	end

	def index
	end

	def show
		@prize = Prize.new
		@subscribers = Subscriber.all
		@subscriber = Subscriber.new
		@referred_by = params[:referred_by] #if !params[:referred_by].nil?
		search = params[:term]
		@result = Subscriber.search(search, @campaign) if search
	end

	def search

	end

	def create
		@campaign = Campaign.new(campaign_params)
		# if !user_signed_in?
		@campaign.user = current_user if current_user
		if @campaign.valid?
			@campaign.save
			redirect_to admin_path(@campaign)
		else
			render :new
		end
	end

	def activate
		@campaign = Campaign.find(params[:id])
		if @campaign.user.nil? && current_user.nil?
			flash[:errors]="Please create a user account"
			redirect_to admin_path(@campaign)
		end
		if @campaign.active
			@campaign.update(active: 0)
		else
			@campaign.update(active: 1, activate_date: Date.today.to_s )
		end
		if @campaign.valid?
			redirect_to @campaign
		else
			flash[:errors]="something went wrong"
			redirect_to admin_path(@campaign)
		end
	end

	def admin
		@campaign = Campaign.find(params[:id])

		@prize = Prize.new
		@prizes = @campaign.prizes

		if current_user != @campaign.user
			redirect_to new_user_session_path
		end
		@subscribers = @campaign.subscribers.all.order("score DESC")
	end

	def stats
		@campaign = Campaign.find(params[:id])

		if current_user != @campaign.user
			redirect_to new_user_session_path
		end

		@subscribers = @campaign.subscribers.all.order("score DESC")
		respond_to do |format|
			format.html
			format.csv do
				headers['Content-Disposition'] = "attachment; filename=\"subscriber-list\""
				headers['Content-Type'] ||= 'text/csv'
			end
		end
	end

	private

		def campaign_params
			params.require(:campaign).permit(:title,:duration, :term)
		end

		def set_campaign
			@campaign = Campaign.find(params[:id])
		end

		# def all_campaigns
		# 	@campaigns = Campaign.all
		# end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

	def subscribers_by_day(campaign)
		results=campaign.subscribers.group("strftime('%Y-%m-%d', created_at)").count

		js= <<-JavaScript
			var label=#{results.keys};
			var data = #{results.values};
		JavaScript

		js.html_safe
	end
end

app/views/campaigns/_form.html.erb
<div class="container">
  <%= form_for campaign do |f| %>
  <%= f.label "Campaign Title" %>
  <%= f.text_field :title, class: "form-control" %><br>
    <div class="form-group">
    <span style="float:left;">Duration:</span><br>
    <%= f.text_field :duration, placeholder: "30", class: "day-size form-control col-sm-10"  %>
    <%= f.label "Days", class: "col-xs-2 control-label days-label" %>
  </div><br><br><br><br>
  <%= f.submit submitbutton, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/campaigns/_progress.html.erb
<div id="year-slider" class="no-ui-slider">
  <div class="slider"></div>
  <ul class="slider-labels eleven-columns" id="sliderthing">
    <li data-id="5">5 min.</li>
    <li data-id="30">30 min.</li>
    <li data-id="60" class="active">1 hr</li>
    <li data-id="360">6 hrs</li>
    <li data-id="720">12 hrs</li>
    <li data-id="1440">24 hrs</li>
  </ul>
</div>

app/views/campaigns/_stats.html.erb
<div class="col-md-12">
	<table style="width:100%;border-style:solid;border-width:2px;border-color:black; padding:10px;">
		<th>Name</th>
		<th>Email</th>
		<th>Points</th>
		<th>Date Created</th>
		<%= render subscribers %>
	</table>
</div>

app/views/campaigns/admin.html.erb
<style>
	td,th,tr,thead,table{
		padding:20px !important;
		border-color:black;
		border-width:1px;
		border-style:solid;
	}
	th{
		background-color:#25CB68;
	}

	table,thead{
		border-radius:3px !important;
	}
</style>
<% if current_user != @campaign.user %>
	You cannot access this page
<% else %>

	<div class="col-md-3" style="background-color:#2E3C54;color:white;height:100vw;">
		Side Bar
	</div>

	<div class="col-md-9">
			<% if current_user == @campaign.user %>

		<% if current_user.nil? && @campaign.user.nil? %>
		<%= render partial: 'devise/registrations/new'%>
		<% end %>


				<div class="row" style="margin:5%;">
					<div class="col-md-10 col-md-offset-1" style="margin-top:20px;margin-bottom:40px;background-color:white;padding:40px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,0.3);border-radius:3px;">
						<div style="text-align:center;">
							<% if !@campaign.active %>
								<%= link_to "Activate Campaign", activate_path, class: "btn btn-primary"  %>
							<% else %>
								<div class="col-md-offset-3 col-md-6">
									<div class="row" style="padding:20px;">
										<% campaign_end = @campaign.activate_date.to_date + @campaign.duration %>
										<div style="font-size:36px;line-height:36px;margin-bottom:0;text-align:center;font-weight:900">
											<span style="margin-top:0;color:black;padding-bottom:0;"><%= count_down = (campaign_end - Date.today).to_i %> Days Left</span><br><span style="color:black;padding-top:0;font-size:18px;">Until Campaign End</span>
										</div>
									</div>
								</div>
								<%= link_to "Deactivate Campaign", activate_path, class: "btn btn-danger", style: "color:white;" %>
							<% end %>
						</div>
					</div>
				</div>


				<div class="row">
					<div class="col-md-10 col-md-offset-1" style="margin-top:20px;margin-bottom:40px;background-color:white;padding:40px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,0.3);border-radius:3px;">
		   				<%= javascript_include_tag  "//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" %>
						<div class='wrapper'>
						  <canvas height='300' id='canvas' width='700'></canvas>
						</div>

						<script>

						var ctx = document.getElementById("canvas").getContext("2d");
						var gradient = ctx.createLinearGradient(0,0,0,400);
						gradient.addColorStop(0, 'rgba(57,231,178,1)');
						gradient.addColorStop(1, 'rgba(3,206,252,1)');
						<%= subscribers_by_day(@campaign) %>
						var myData = {
						  labels: label,
						  datasets: [{
						    fillColor: gradient,
						    strokeColor: "rgba(3,206,252,1)",
						    pointColor: "rgba(220,220,220,1)",
						    pointStrokeColor: "rgba(3,206,252,1)",
						    data: data
						  }]
						}

						new Chart(document.getElementById("canvas").getContext("2d")).Line(myData)

						</script>
					</div>
				</div>

				<% if !@campaign.active %>
					<div class="row" style="margin:5%;">
						<%= render partial: 'prizes/form', locals:{prize: @prize, campaign: @campaign} %>
					</div>
					<div class="row">
						<div class="col-md-8 col-md-offset-2" style="background-color:white;padding:40px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,0.3);border-radius:3px;">
							<h1>Perks</h1>
							<%= render @prizes %>
						</div>
					</div>
				<% end %>
			<% end %>


		<div class="row">
			<div class="col-md-10 col-md-offset-1" style="margin-top:20px;margin-bottom:40px;background-color:white;padding:40px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,0.3);border-radius:3px;">
				<h1>Total Subscribers Gained from this Campaign:
					<span style="color:#25CB68;"><%= @subscribers.count %></span>
				</h1>
				<div style="text-align:center; color:white;padding:10px;">
					<%= link_to "Download List", stats_path(format: :csv), class: "btn btn-primary", style: "color:white;" %>
				</div>
				<div class="row" style="margin:5%;">
					<%= render partial: 'campaigns/stats', locals: {subscribers: @subscribers} %>
				</div>
			</div>
		</div>
	</div>

<% end%>

<script>
$(document).on('submit','#new_user',function(event){
			event.preventDefault()
			debugger
			let $signup = $(this).serialize();
		  $.post('/users', $signup)
		    .then((data)=>{
		      debugger
		    })
		    .catch((error)=>{
		      debugger
		    })
	})
</script>

app/views/campaigns/index.html.erb
index.html.erb

app/views/campaigns/new.html.erb
<style>

body{
background:#171A3D !important;
}

</style>

<div class="row">
<div  class="col-md-12 outer-box"></div>
	<div class="col-md-6 col-md-offset-3 fancy-box">
		<%= render partial: 'campaigns/form', locals: {campaign: @campaign, submitbutton: "Create Campaign"}%>
	</div>
	<div class="col-md-12"></div>
</div>

app/views/campaigns/show.html.erb
<% if params[:confirmation] %>

	<div>
	<%=confirmation(params[:subscriber],params[:checkin])%>
	</div>

<% end %>



<% if @campaign.active %>

	<!-- Start main campaign section -->
	<div id="gradient">
		<div class="container">
			<div class="col-md-offset-3 col-md-6">
				<div class="row" style="padding:20px;">
					<% campaign_end = @campaign.activate_date.to_date + @campaign.duration %>
					<div style="font-size:36px;line-height:36px;margin-bottom:0;text-align:center;font-weight:900">
						<span style="margin-top:0;color:white;padding-bottom:0;"><%= count_down = (campaign_end - Date.today).to_i %> Days Left</span><br><span style="color:white;padding-top:0;font-size:18px;">Until Campaign End</span>
					</div>
				</div>
			</div>
		</div>

	<!-- Main Box for our Columns-->
		<div style="padding-bottom:50px !important;">
			<div>
			<!-- Column Left -->
				<div class="col-md-3">
					<div style="margin-top:100px;padding:10px;border-radius:4px;padding:20px;border-color:#F1EEEA;border-style:solid;border-width:1px;background-color:#FCFCFB;">
						<h4>Campaign Details</h4>
						<div>
							Describe the details of your campaign. Why should users subscribe?
						</div>
					</div>
					<div style="margin-top:20px; padding:10px;border-radius:4px;padding:20px;border-color:#F1EEEA;border-style:solid;border-width:1px;background-color:#FCFCFB;">
						<h4>Company Info</h4>
						<div>
							<a href="#">Visit Site</a>
						</div>
					</div>
				</div>


			<!-- Column Center -->
				<div style="margin-bottom:100px;" class="col-md-6">
					<div class="row " style=" background-color:#ffffff; border-radius:4px; padding-top:0px;padding-bottom:150px !important;border-style:solid;border-width:1px;border-color:#F1EEEA;">

						<div style="padding:20px;border-bottom-color:#F1EEEA;border-bottom-style:solid;border-bottom-width:1px;background-color:#FCFCFB;">
							<div style="text-align:center;">
								<div style="text-align:center; position:relative;">
									<%= image_tag ('startup.png'), class: "header-img", style: "width:80px" %>
								</div>
								<h3><%= @campaign.title %></h3>
							</div>
						</div>

						<div style="margin-top:20px" class="container">
							<%= form_for([@campaign, @subscriber]) do |f| %>
								<%= f.label :name, "Name" %>
								<%= f.text_field :name, class: "form-control" %><br>
								<%= f.label :email, "Email" %>
								<%= f.text_field :email, class: "form-control" %><br>
								<%= f.hidden_field :referred_by, value: @referred_by  %>
								<div style="text-align:center; width:100%;display:inline-block; position:relative;">
									<div style="padding:5px; width:49%; text-align:center !important; float:left;display:inline !important;"><%= f.submit "Join Waitlist", class: "btn btn-1" %></div>
									<div style="width:49%; padding:5px; text-align:center !important; float:right;display:inline !important;"><%= f.submit "Check Your Score", class: "btn btn-1" %></div>
								</div>
							<% end %>
						</div>
					</div>
				</div>
<style>
.post-container {

}
.post-thumb {
    float: left
}
.post-thumb img {
    display: block
}
.post-content {

}
.post-title {
    font-weight: bold;
    font-size: 100%
}

</style>
			<!-- Column Right -->
				<div class="col-md-3">
					<div style="margin-top:100px;padding:10px;border-radius:4px;padding:20px;border-color:#F1EEEA;border-style:solid;border-width:1px;background-color:#FCFCFB;">
						<h4>View Perks</h4>
					</div>
					<% if @campaign.prizes %>
						<div style="padding:10px;border-radius:4px;padding:20px;border-color:#F1EEEA;border-style:solid;border-width:1px;background-color:#FCFCFB;">
								<% @campaign.prizes.each do |prize| %>
									<div class="post-container" style="text-decoration:none;list-style-type:none;">
										<%= link_to image_tag('star.png'), "#", class: "post-thumb" %>
										<div class="post-content">
											<p class="post-title" style="text-decoration:none;list-style-type:none;">Perk: <strong style="color:#25CB68;"><%= prize.title %></strong></p>
											<p style="text-decoration:none;list-style-type:none;">Referrals Needed: <strong><%= prize.milestone %></strong></p>
											<br>
										</div>
									</div>
								<% end %>
						</div>
					<% end %>


				</div>
			</div>
		</div>
	</div>
	<!-- End main campaign section -->
	<style>
	 input{
	    display: inline-block;
	    width: 300px;
	    margin-right: 5px;

	    font-size: 14px;
	    font-weight: normal;
	    line-height: 20px;
	    display: block;
	    width: 100%;
	    height: 40px;
	    padding: 5px 15px;
	    background-color: #ffffff;
	    border: 1px solid #dddddd;

	  -webkit-appearance: none;
	    border-radius: 2px;
	  }
	</style>

	<div class="container">

	</div>

	<div style="border-color:#F1EEEA;border-style:solid;border-width:1px;background-color:white;">
	<div class="container">
		<div class="row" style="padding-top:50px;padding-bottom:50px;">
				<div class="col-md-6">
					<div>
						<%= form_tag(campaign_path(@campaign), method: :get) do %>
							<label style="font-size:18px; text-align:center !important;padding-bottom:10px;">Check Your Campaign Score</label><br>
							<%= text_field_tag :term, "", {placeholder:"Enter your Email"} %><br>
							<%= submit_tag "Check Score", {class: "btn"} %>
						<% end %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="container">
						<% if !@result.nil? && !@result.empty? %>
							<ul style="padding-top:20px; text-decoration:none;list-style-type:none;">
								<li style="text-decoration:none;list-style-type:none; font-size:18px;"><strong>You have earned <span style="color:#25CB68;"><%= @result[0].score %></span> points!</strong></li><br>
								<li style="display:inline;text-decoration:none;list-style-type:none;font-size:18px;"><strong>Share Your Link: </strong><input style="display:inline;" class="form-control" readonly type="text" value="<%= campaign_url + '?referred_by=' + @result[0].referral_code %>"/></li>
							</ul>
						<% end %>
					</div>
				</div>
		</div>
	</div>
	</div>
<% end %>

	<script type="text/javascript">
	    $(window).load(function(){
	        $('#myModal').modal('show');
	    });
	</script>

app/views/campaigns/stats.csv.erb
<%- headers = ['Name', 'Email'] -%>
<%= CSV.generate_line headers %>
<%- @subscribers.each do |sub| -%>
<%= CSV.generate_line([sub.name, sub.email]) -%>
<%- end -%>